### PR TITLE
Merge residuals analysis branch into master

### PR DESCRIPTION
**Pull request by megcrow**
This branch has the most updated neros functions, model code, and fit analysis code.

### CODE REVIEW

**Comment by RichardOtt** [comment]
A few comments:
- Do we want to have all those graphs and output files in the master branch? Generally it's not a good idea since they change every time the code is run
- By that same logic, we probably don't want the notebook with everything run and all results checked into master
- If that's something we *do* want, we probably want it do it with a different name, or in a sub-folder, so there's a "clean" copy
- Do we want to figure out the gaussian fits before merging? Or let that be a work in progress?
- We're going to have to be very careful about this merge - git looks like it's trying to be too clever here.  It's trying to recognize the Neros_v4_test.py and Neros.py as the same file and merging them there.  We'd have to dig through the history as to _why_ it thinks that

**Comment by megcrow** [comment]
Thanks Rich, I cleaned out the graphs and outputs and cleared the jupyter notebooks (see new commit). I made a backup branch residuals_analysis_mfc_v2 with all of that stuff in there in case we want to have them easily accessed at some point.

I'll follow up with you about the Gaussian fits on slack.

**Comment by RichardOtt** [comment]
Small points
- We should make some placeholder to create the `fit-analysis-plots/MWMcGaugh` directory
- Your calculation of FWHM is *assuming* a Gaussian distribution
- We'll need to resolve this merge conflict before we can actually do anything

**Review by RichardOtt — APPROVED** [review]
I think this is in good shape, as a base to work off of

**Pull request merged**
